services:
  tutorbot:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      # Mount the current directory to /app for live code changes
      - .:/app
      # Exclude node_modules and other build artifacts
      - /app/__pycache__
      - /app/.git
    env_file:
      - .env