#!/bin/bash

# TutorBot - Help Script
# Shows all available commands and shortcuts

echo "🤖 TutorBot - Available Commands"
echo "================================"
echo ""

echo "🚀 QUICK COMMANDS (aliases):"
echo "  wipe        - Wipe all contacts and conversations (short)"
echo "  wipebot     - Wipe all contacts and conversations (long)"
echo "  wipeall     - Wipe all labels and attributes (short)"
echo "  wipeallbot  - Wipe all labels and attributes (long)"
echo "  start       - Quick Docker restart (short)"
echo "  startbot    - Full Docker restart (down + up) (long)"
echo "  logs        - Show Docker logs (short)"
echo "  logsbot     - Show Docker logs (long)"
echo "  status      - Show Docker status (short)"
echo "  statusbot   - Show Docker status (long)"
echo "  validate    - Validate project structure (short)"
echo "  validatebot - Validate project structure (long)"
echo "  help        - Show all commands (short)"
echo "  helpbot     - Show all commands (long)"
echo ""

echo "📁 PROJECT STRUCTURE:"
echo "  /home/stephen/tutorbot/"
echo "  ├── main.py                    # Core Flask application"
echo "  ├── requirements.txt           # Python dependencies"
echo "  ├── wipe.sh                    # Quick contact wipe script"
echo "  ├── help.sh                    # This help script"
echo "  ├── config/                    # Configuration files"
echo "  │   ├── contact_attributes.yaml"
echo "  │   ├── conversation_attributes.yaml"
echo "  │   ├── labels_lean.yaml"
echo "  │   └── automations.yaml"
echo "  ├── scripts/                   # Setup and utility scripts"
echo "  │   ├── setup_attributes.py"
echo "  │   ├── setup_labels.py"
echo "  │   ├── setup_all.py"
echo "  │   ├── wipe_contacts.py"
echo "  │   └── validate_structure.py"
echo "  └── docs/                      # Documentation"
echo "      └── README_chatwoot_setup.md"
echo ""

echo "🔧 SETUP COMMANDS:"
echo "  python3 scripts/setup_all.py           # Setup everything (attributes + labels)"
echo "  python3 scripts/setup_attributes.py    # Setup custom attributes only"
echo "  python3 scripts/setup_labels.py        # Setup labels only"
echo "  python3 scripts/validate_structure.py  # Validate project structure"
echo ""

echo "🧪 TESTING COMMANDS:"
echo "  ./wipe.sh                              # Quick contact wipe (automatic)"
echo "  ./wipe_all.sh                          # Quick data wipe (labels + attributes)"
echo "  python3 scripts/wipe_contacts.py       # Manual contact wipe"
echo "  python3 scripts/wipe_contacts.py --auto-wipe  # Auto-wipe (no confirmation)"
echo "  python3 scripts/wipe_contacts.py --force      # Manual wipe (with confirmation)"
echo "  python3 scripts/wipe_all.py            # Manual data wipe"
echo "  python3 scripts/wipe_all.py --auto-wipe       # Auto data wipe (no confirmation)"
echo "  docker-compose restart                 # Quick restart (keep container)"
echo "  docker-compose down && docker-compose up -d  # Full restart (rebuild)"
echo "  docker-compose logs -f                 # Show live logs"
echo "  docker-compose ps                      # Show container status"
echo ""

echo "📋 ENVIRONMENT VARIABLES:"
echo "  CW_URL=https://crm.stephenadei.nl"
echo "  CW_ACC_ID=1"
echo "  CW_ADMIN_TOKEN=your_admin_token"
echo "  CW_TOKEN=your_bot_token"
echo ""

echo "🌐 WEBHOOK URL:"
echo "  https://your-domain.com/cw"
echo ""

echo "💡 TIPS:"
echo "  • Always run commands from /home/stephen/tutorbot/"
echo "  • Use aliases for quick access: wipebot, startbot, validatebot"
echo "  • Check .cursorrules for development guidelines"
echo "  • Run validatebot before making changes"
echo ""

echo "📚 DOCUMENTATION:"
echo "  docs/README_chatwoot_setup.md          # Complete setup guide"
echo "  .cursorrules                           # Development guidelines"
echo ""

echo "🎯 QUICK START:"
echo "  1. validate                            # Validate structure"
echo "  2. wipe                                # Clear contacts"
echo "  3. start                               # Start server"
echo "  4. Test with WhatsApp messages"
echo "" 