#!/bin/bash

# TutorBot - Help Script
# Shows all available commands and shortcuts

echo "🤖 TutorBot - Available Commands"
echo "================================"
echo ""

echo "🚀 QUICK COMMANDS (aliases):"
echo "  wipe        - Wipe all contacts and conversations (short)"
echo "  wipebot     - Wipe all contacts and conversations (long)"
echo "  wipeall     - Wipe all labels and attributes (short)"
echo "  wipeallbot  - Wipe all labels and attributes (long)"
echo "  start       - Quick Docker restart (short)"
echo "  startbot    - Full Docker restart (down + up) (long)"
echo "  logs        - Show Docker logs (short)"
echo "  logsbot     - Show Docker logs (long)"
echo "  clearlogs   - Clear Docker logs (short)"
echo "  clearlogsbot - Clear Docker logs (long)"
echo "  clearlogsall - Clear all logs and Docker cache (thorough)"
echo "  status      - Show Docker status (short)"
echo "  statusbot   - Show Docker status (long)"
echo "  validate    - Validate project structure (short)"
echo "  validatebot - Validate project structure (long)"
echo "  help        - Show all commands (short)"
echo "  helpbot     - Show all commands (long)"
echo ""

echo "🔧 DEVELOPMENT COMMANDS:"
echo "  ./scripts/dev/dev.sh restart              # Quick restart (for env changes)"
echo "  ./scripts/dev/dev.sh rebuild              # Rebuild and restart (for deps)"
echo "  ./scripts/dev/dev.sh logs                 # Show live logs"
echo "  ./scripts/dev/dev.sh clean                # Clean and rebuild everything"
echo ""
echo "📋 LOG MANAGEMENT:"
echo "  logs                                    # Show live logs"
echo "  logsbot                                 # Show live logs (long)"
echo "  clearlogs                               # Clear Docker logs"
echo "  clearlogsbot                            # Clear logs with confirmation"
echo "  clearlogsall                            # Clear all logs and cache"
echo "  docker-compose logs --tail=50           # Show last 50 lines"
echo "  docker-compose logs --since=1h          # Show logs from last hour"
echo "  docker-compose logs --clear             # Clear all logs"
echo "  docker system prune -f                  # Clear all Docker cache"
echo ""

echo "🐛 DEBUG COMMANDS (aliases):"
echo "  debug       - Toggle debug mode"
echo "  debugbot    - Toggle debug mode (long)"
echo "  debugon     - Enable public debug mode"
echo "  debugoff    - Disable debug mode"
echo "  debugprivate - Enable private debug mode"
echo "  debugconsole - Enable console debug mode"
echo "  debugstatus - Show debug status"
echo ""

echo "✅ CONFIRMATION COMMANDS (aliases):"
echo "  confirm     - Toggle confirmation mode"
echo "  confirmbot  - Toggle confirmation mode (long)"
echo "  confirmon   - Enable confirmations"
echo "  confirmoff  - Disable confirmations"
echo "  confirmstatus - Show confirmation status"
echo ""

echo "📋 ENVIRONMENT COMMANDS (aliases):"
echo "  export_env  - Export environment variables from .env"
echo "  exportenv   - Export environment variables (short)"
echo "  source scripts/dev/export_env.sh           # Manual export"
echo ""

echo "📁 PROJECT STRUCTURE:"
echo "  /home/stephen/tutorbot/"
echo "  ├── main.py                    # Core Flask application"
echo "  ├── requirements.txt           # Python dependencies"
echo "  ├── docker-compose.yml         # Docker configuration"
echo "  ├── Dockerfile                 # Docker image"
echo "  ├── .env                       # Environment variables (not in git)"
echo "  ├── env_example.txt            # Environment template"
echo "  ├── scripts/help.sh            # This help script"
echo "  ├── tests/                     # Automated tests (unit & integration)"
echo "  │   ├── run_tests.py           # Test runner for all tests"
echo "  │   ├── test_main.py           # Main application unit tests"
echo "  │   ├── test_config.py         # Configuration tests"
echo "  │   ├── test_prefill_overview.py # Prefill functionality tests"
echo "  │   └── test_setup.py          # Setup tests"
echo "  ├── scripts/                   # Organized scripts directory"
echo "  │   ├── cw_api.py              # Chatwoot API utilities"
echo "  │   ├── help.sh                # This help script"
echo "  │   ├── dev/                   # Development scripts"
echo "  │   │   ├── dev.sh             # Development shortcuts"
echo "  │   │   └── export_env.sh      # Environment export script"
echo "  │   ├── data/                  # Data management scripts"
echo "  │   │   ├── wipe.sh            # Quick contact wipe script"
echo "  │   │   ├── wipe_all.sh        # Quick data wipe script"
echo "  │   │   ├── wipe_contacts.py   # Manual contact wipe"
echo "  │   │   ├── wipe_all.py        # Manual data wipe"
echo "  │   │   └── cleanup_all.py     # Clean up all data"
echo "  │   ├── debug/                 # Debug and confirmation scripts"
echo "  │   │   ├── debug_*.sh         # Debug management scripts"
echo "  │   │   └── confirm_*.sh       # Confirmation management scripts"
echo "  │   ├── setup/                 # Setup and configuration scripts"
echo "  │   │   ├── setup_attributes.py    # Setup custom attributes"
echo "  │   │   ├── setup_labels.py        # Setup labels"
echo "  │   │   ├── setup_all.py           # Setup everything"
echo "  │   │   ├── setup_automation_rules.py"
echo "  │   │   ├── setup_chatwoot.py      # Setup Chatwoot configuration"
echo "  │   │   └── setup_custom_attributes.py"
echo "  │   ├── analysis/              # Analysis and audit scripts"
echo "  │   │   ├── analyze_logs.py        # Analyze log files"
echo "  │   │   ├── check_inboxes.py       # Check inbox status"
echo "  │   │   ├── list_contact_languages.py"
echo "  │   │   ├── list_automation.py     # List automation rules"
echo "  │   │   ├── audit_attributes.py    # Audit custom attributes"
echo "  │   │   └── validate_structure.py  # Validate project structure"
echo "  │   └── testing/               # Manual testing tools"
echo "  │       ├── show_prefill_overview.py # Show prefill overview"
echo "  │       ├── test_bot.py            # Manual bot testing"
echo "  │       ├── test_chatwoot_api.py   # Manual API testing"
echo "  │       ├── test_input_select.py   # Input select testing"
echo "  │       ├── test_real_message.py   # Real message testing"
echo "  │       └── test_real_conversation.py # Real conversation testing"
echo "  ├── config/                    # Configuration files"
echo "  │   ├── contact_attributes.yaml"
echo "  │   ├── conversation_attributes.yaml"
echo "  │   ├── labels_lean.yaml"
echo "  │   └── automations.yaml"
echo "  ├── docker/                    # Docker documentation"
echo "  │   └── README.md              # Docker setup and usage"
echo "  └── docs/                      # Documentation"
echo "      ├── README_chatwoot_setup.md"
echo "      ├── WHATSAPP_FORMATTING.md"
echo "      ├── INTEGRATION_ROADMAP.md"
echo "      └── CURRENT_MOCKED_FUNCTIONS.md"
echo ""

echo "🔧 SETUP COMMANDS:"
echo "  python3 scripts/setup/setup_all.py           # Setup everything (attributes + labels)"
echo "  python3 scripts/setup/setup_attributes.py    # Setup custom attributes only"
echo "  python3 scripts/setup/setup_labels.py        # Setup labels only"
echo "  python3 scripts/setup/setup_automation_rules.py  # Setup automation rules"
echo "  python3 scripts/setup/setup_chatwoot.py      # Setup Chatwoot configuration"
echo "  python3 scripts/analysis/validate_structure.py  # Validate project structure"
echo ""

echo "🧪 TESTING COMMANDS:"
echo "  ./scripts/data/wipe.sh                      # Quick contact wipe (automatic)"
echo "  ./scripts/data/wipe_all.sh                  # Quick data wipe (labels + attributes)"
echo "  python3 scripts/data/wipe_contacts.py       # Manual contact wipe"
echo "  python3 scripts/data/wipe_contacts.py --auto-wipe  # Auto-wipe (no confirmation)"
echo "  python3 scripts/data/wipe_contacts.py --force      # Manual wipe (with confirmation)"
echo "  python3 scripts/data/wipe_all.py            # Manual data wipe"
echo "  python3 scripts/data/wipe_all.py --auto-wipe       # Auto data wipe (no confirmation)"
echo "  python3 scripts/data/cleanup_all.py         # Clean up all data"
echo "  docker-compose restart                 # Quick restart (keep container)"
echo "  docker-compose down && docker-compose up -d  # Full restart (rebuild)"
echo "  docker-compose logs -f                 # Show live logs"
echo "  docker-compose logs --tail=50          # Show last 50 log lines"
echo "  docker-compose logs --since=1h         # Show logs from last hour"
echo "  docker-compose ps                      # Show container status"
echo "  docker-compose logs --clear            # Clear all logs"
echo "  docker system prune -f                 # Clear all Docker logs and cache"
echo ""

echo "🧪 AUTOMATED TESTS (tests/):"
echo "  python3 tests/run_tests.py                 # Run all automated tests"
echo "  python3 tests/run_tests.py --category core # Run core functionality tests"
echo "  python3 tests/run_tests.py --category api  # Run API integration tests"
echo "  python3 tests/test_prefill_overview.py     # Test prefill overview functionality"
echo ""
echo "🔧 MANUAL TESTING TOOLS (scripts/testing/):"
echo "  python3 scripts/testing/show_prefill_overview.py # Show prefill overview for conversation"
echo "  python3 scripts/testing/test_real_message.py     # Test with real message"
echo "  python3 scripts/testing/test_real_conversation.py # Test with real conversation"
echo "  python3 scripts/testing/test_bot.py              # Test bot functionality"
echo "  python3 scripts/testing/test_chatwoot_api.py     # Test Chatwoot API"
echo "  python3 scripts/testing/test_input_select.py     # Test input selection"
echo ""

echo "🧪 COMPREHENSIVE TEST SUITE:"
echo "  python3 tests/test_setup.py            # Verify test environment setup"
echo "  python3 tests/run_tests.py             # Run all tests"
echo "  python3 tests/run_tests.py --list-categories # List available test categories"
echo "  python3 tests/run_tests.py --category core   # Run core functionality tests"
echo "  python3 tests/run_tests.py --category flow   # Run flow tests"
echo "  python3 tests/run_tests.py --category api    # Run API tests"
echo "  python3 tests/run_tests.py --test TestTranslation.test_basic_translation  # Run single test"
echo "  python3 tests/run_tests.py --verbose         # Run tests with verbose output"
echo ""

echo "🧪 TEST CATEGORIES:"
echo "  core        - Core functionality (translation, message, utility)"
echo "  flow        - User flows (intake, menu, integration)"
echo "  api         - API integration (openai, payment, webhook)"
echo "  translation - Translation system tests"
echo "  message     - Message handling tests"
echo "  openai      - OpenAI integration tests"
echo "  prefill     - Prefill functionality tests"
echo "  segment     - Segment detection tests"
echo "  planning    - Planning functionality tests"
echo "  payment     - Payment functionality tests"
echo "  intake      - Intake flow tests"
echo "  menu        - Menu handling tests"
echo "  webhook     - Webhook handling tests"
echo "  utility     - Utility function tests"
echo "  email       - Email and payment handling tests"
echo "  integration - Integration scenario tests"
echo "  error       - Error handling tests"
echo ""

echo "📁 ORGANIZED SCRIPTS:"
echo "  ./scripts/                              # All scripts directory"
echo "  ./scripts/dev/                          # Development scripts"
echo "  ./scripts/data/                         # Data management scripts"
echo "  ./scripts/debug/                        # Debug and confirmation scripts"
echo "  ./scripts/setup/                        # Setup and configuration scripts"
echo "  ./scripts/analysis/                     # Analysis and audit scripts"
echo "  ./scripts/testing/                      # Testing scripts"
echo ""

echo "🔧 SCRIPT CATEGORIES:"
echo "  Development:    ./scripts/dev/dev.sh"
echo "  Data Management: ./scripts/data/wipe.sh, ./scripts/data/wipe_all.sh"
echo "  Debug Management: ./scripts/debug/debug_*.sh"
echo "  Confirmation:   ./scripts/debug/confirm_*.sh"
echo "  Environment:    ./scripts/dev/export_env.sh"
echo "  Setup:          ./scripts/setup/setup_*.py"
echo "  Analysis:       ./scripts/analysis/*.py"
echo "  Manual Testing: ./scripts/testing/*.py"
echo ""

echo "📋 ENVIRONMENT VARIABLES:"
echo "  CW_URL=https://crm.stephenadei.nl"
echo "  CW_ACC_ID=1"
echo "  CW_ADMIN_TOKEN=your_admin_token"
echo "  CW_TOKEN=your_bot_token"
echo "  CW_HMAC_SECRET=your_hmac_secret"
echo "  OPENAI_API_KEY=your_openai_key"
echo "  STRIPE_WEBHOOK_SECRET=your_stripe_secret"
echo ""

echo "🌐 WEBHOOK URL:"
echo "  https://your-domain.com/cw"
echo ""

echo "💡 TIPS:"
echo "  • Always run commands from /home/stephen/tutorbot/"
echo "  • Use aliases for quick access: wipebot, startbot, validatebot"
echo "  • Check .cursorrules for development guidelines"
echo "  • Run validatebot before making changes"
echo "  • Use ./scripts/dev/dev.sh for development tasks"
echo "  • Use exportenv before running Python scripts directly"
echo "  • Debug commands help with troubleshooting"
echo "  • Analysis scripts help understand system state"
echo ""

echo "📚 DOCUMENTATION:"
echo "  docs/README_chatwoot_setup.md          # Complete setup guide"
echo "  docs/WHATSAPP_FORMATTING.md            # WhatsApp formatting guide"
echo "  docs/INTEGRATION_ROADMAP.md            # Calendar & payment integration roadmap"
echo "  docs/CURRENT_MOCKED_FUNCTIONS.md       # Mocked functions overview"
echo "  .cursorrules                           # Development guidelines"
echo "  README.md                              # Project overview"
echo ""

echo "🎯 QUICK START:"
echo "  1. validate                            # Validate structure"
echo "  2. exportenv                           # Export environment variables"
echo "  3. wipe                                # Clear contacts"
echo "  4. start                               # Start server"
echo "  5. Test with WhatsApp messages"
echo ""

echo "🔍 DEBUGGING & ANALYSIS:"
echo "  docker-compose logs -f tutorbot        # Live logs"
echo "  docker-compose exec tutorbot bash      # Enter container"
echo "  python3 tests/run_tests.py --category prefill # Test prefill"
echo "  python3 scripts/analysis/analyze_logs.py        # Analyze log files"
echo "  python3 scripts/analysis/check_inboxes.py       # Check inbox status"
echo "  python3 scripts/analysis/list_contact_languages.py  # List contact languages"
echo "  python3 scripts/analysis/list_automation.py     # List automation rules"
echo "  python3 scripts/analysis/audit_attributes.py    # Audit custom attributes"
echo "  debugstatus                            # Check debug status"
echo "  confirmstatus                          # Check confirmation status"
echo ""

echo "🚀 INTEGRATION STATUS:"
echo "  ✅ Core Bot Logic - Fully functional"
echo "  ✅ Chatwoot Integration - Fully functional"
echo "  ✅ Prefill & Intake System - Fully functional"
echo "  ✅ WhatsApp Formatting - Fully functional"
echo "  ✅ Menu System - Fully functional"
echo "  🔄 Calendar Integration - Partially implemented (mocked)"
echo "  🔄 Payment Integration - Partially implemented (mocked)"
echo ""

echo "📋 NEXT STEPS:"
echo "  • Calendar Integration: Google Calendar API setup"
echo "  • Payment Integration: Stripe API setup"
echo "  • See docs/INTEGRATION_ROADMAP.md for detailed plan"
echo "" 